  #define Start_Screen 0
  #define CD_Content 1
  #define whats_new 2
  #define LAD_FBD 3
  #define compatibility 4
  #define internet 5
  #define basic_skills 6
  #define Introduction 7
  #define window___DrawingView 8
  #define Programming 9
  #define program___new 10
  #define block___select 11
  #define place_blocks 12
  #define contextsensitive_menu 13
  #define availability_of_blocks 14
  #define connecting_blocks 15
  #define Edit_program 16
  #define mark_objects 17
  #define edit_marked_objects 18
  #define replace_blocks 19
  #define cut_connections 20
  #define Program_documentation 21
  #define Start_simulation 22
  #define Info_window 23
  #define simulated_inputs 24
  #define simalation_and_messages 25
  #define alternative_operation 26
  #define Controlling_the_simulation_time 27
  #define kind_of_input 28
  #define power_off 29
  #define simulation_of_outputs 30
  #define force___binaryOutput 31
  #define param_during_simulation 32
  #define Save_Program 33
  #define example___introduction 34
  #define example___task 35
  #define example___oldfashioned_solution 36
  #define example___new_with_logo 37
  #define example___projektdata 38
  #define example___placing_blocks 39
  #define example___connecting_blocks 40
  #define example___tidy_up 41
  #define example___optimize_view 42
  #define example___start_simulation 43
  #define example___programmtest 44
  #define example___documentation 45
  #define example___download 46
  #define toolbar___Fup 47
  #define toolbar___drawing 48
  #define toolbar___catalogue 49
  #define tool___selection 50
  #define tool___text 51
  #define tool___scissors 52
  #define tool___connector 53
  #define block___Constant 54
  #define block___Contact 55
  #define block___AnalogContact 56
  #define block___NegativContact 57
  #define block___Coil 58
  #define block___AnalogCoil 59
  #define block___NegativCoil 60
  #define block___InternMarker 61
  #define block___Base 62
  #define block___Special 63
  #define extra___simulation 64
  #define menue_bar___introduction 65
  #define file___base 66
  #define file___new 67
  #define file___open 68
  #define file___close 69
  #define file___CloseAll 70
  #define file___save 71
  #define file___SaveAs 72
  #define file___pageformat 73
  #define file___PrintPreview 74
  #define file___print 75
  #define file___properties 76
  #define file_properties_common 77
  #define file_properties_comment 78
  #define file_properties_statistics 79
  #define file_properties_pagenumbers 80
  #define dialog___PCLogoProperty 81
  #define dialog___Comparator 82
  #define file___convertToFup 83
  #define file___convertToKop 84
  #define file___messagetextsettings 85
  #define file___exit 86
  #define edit___base 87
  #define edit___undo 88
  #define edit___redo 89
  #define edit___delete 90
  #define edit___cut 91
  #define edit___copy 92
  #define edit___paste 93
  #define edit___MarkAll 94
  #define edit___GotoBlock 95
  #define edit___MarkedToForeground 96
  #define edit___MarkedToBackground 97
  #define edit___ConnectorNames 98
  #define edit___BlockProperties 99
  #define edit___BlockPropertiesAll 100
  #define edit___AutoCutConnections 101
  #define format___base 102
  #define format___font 103
  #define format___align 104
  #define format___align___vertical 105
  #define format___align___horizontal 106
  #define format___align___automatically 107
  #define format___grid 108
  #define format___AlignToGrid 109
  #define view___base 110
  #define view___zoom 111
  #define view___blowup 112
  #define view___reduce 113
  #define view___marker 114
  #define view___symbolbars 115
  #define view___MessageWindow 116
  #define view___Statusbar 117
  #define view___tooltipps 118
  #define extra___base 119
  #define extras___transfer 120
  #define extra___transfer___toLogo 121
  #define extra___transfer___toPC 122
  #define extra___transfer___changeDeviceState 123
  #define extras___transfer___clock 124
  #define extras___transfer___SummerWintertime 125
  #define extras___transfer___HoursClock 126
  #define extra___clearProg 127
  #define extras___DetermineLOGO 128
  #define extras___Hardware 129
  #define extra___onlinetest 130
  #define extras___modemInfo 131
  #define extras___selectConfigModem 132
  #define extras___selectRemoteConfiguration 133
  #define extras___setRemoteModemCommand 134
  #define extras___configRemoteModem 135
  #define extras___selectLocalConfiguration 136
  #define extras___setLocalModemCommand 137
  #define extras___configTelNumber 138
  #define extras___disconnectmodem 139
  #define extras___options 140
  #define extras___options___editor 141
  #define extras___options___language 142
  #define Extras___options___documentview 143
  #define extras___options___screen 144
  #define extras___options___print 145
  #define extras___options___CutConnections 146
  #define extras___options___port 147
  #define extras___options___simulation 148
  #define extras___options___colors 149
  #define extras___options___lookandfeel 150
  #define window___base 151
  #define window___ArrangeVertical 152
  #define window___ArrangeHorizontal 153
  #define window___ArrangeCascaded 154
  #define window___splitVertical 155
  #define window___SplitHorizontal 156
  #define window___unsplit 157
  #define Fenster_Auswahlliste 158
  #define help___base 159
  #define help___content 160
  #define help___ContextSensitive 161
  #define help___abaout 162
  #define help___update 163
  #define statusline 164
  #define FunctionKeys 165
  #define intro___programming 166
  #define LOGO___Hardware 167
  #define MemoryUsage 168
  #define LOGO___Memory 169
  #define Blocks 170
  #define blocknumbers 171
  #define convert_programs 172
  #define block___Input 173
  #define block___Input___ASi 174
  #define block___Input___Analog 175
  #define working_with_Analogvalues 176
  #define working_with_Analogvalues2 177
  #define working_with_Analogvalues3 178
  #define working_with_Analogvalues4 179
  #define working_with_Analogvalues5 180
  #define block___Output 181
  #define block___Output___ASi 182
  #define block___Marker 183
  #define block___Fixed 184
  #define block___KeyInput 185
  #define block___TDFunctionKeyInput 186
  #define block___VirtualOutput 187
  #define block___ShiftRegisterInput 188
  #define block___AnalogOutput 189
  #define block___And 190
  #define block___PecAnd 191
  #define block___Nand 192
  #define block___PecNand 193
  #define block___Or 194
  #define block___Nor 195
  #define block___Xor 196
  #define block___Not 197
  #define block___OnDelay 198
  #define block___OffDelay 199
  #define block___OnOffDelay 200
  #define block___RetentiveOnDelay 201
  #define block___LatchingRelay 202
  #define block___PulseRelay 203
  #define block___WipingRelay 204
  #define block___WipingRelayPEC 205
  #define block___Clock 206
  #define block___YearClock 207
  #define block___Counter 208
  #define block___HoursCounter 209
  #define block___SymPulseGenerator 210
  #define block___AsymPulseGenerator 211
  #define block___Random 212
  #define block___Trigger 213
  #define block___AnalogTrigger 214
  #define block___AnalogDifferenceTrigger 215
  #define block___AnalogComparator 216
  #define block___AnalogWatchdog 217
  #define block___StairsSwitch 218
  #define block___ComfortSwitch 219
  #define block___Message 220
  #define block___Message___plain 221
  #define block___Softkey 222
  #define block___ShiftRegister 223
  #define block___MathDetection 224
  #define block___Amplifier 225
  #define controller___basics 226
  #define controller___basics___1 227
  #define controller___basics___2 228
  #define block___PID 229
  #define block___RampControl 230
  #define block___AnalogMux 231
  #define block___PWM 232
  #define block___AnalogMaths 233
  #define examples 234
  #define example___ComfortableSwitch 235
  #define example___aircondition 236
  #define example___factorydoor 237
  #define example___pt100 238
  #define help___tipps___tricks 239
  #define dialog___DateInputPanel 240
  #define Description_of_surface 241
  #define DrawingViewMenuInfo 242
  #define window___DrawingView 243
  #define BlockMenuInfo 244
  #define InputIfcFigureMenuInfo 245
  #define ConnectionMenuInfo 246
  #define OutputIfcFigureMenuInfo 247
  #define MultiSelectionMenuInfo 248
  #define CuttedConnectionMenuInfo 249
  #define CutConnectFigureMenuInfo 250
  #define block___Comment 251
  #define CommentMenuInfo 252
  #define toolbar___simulation___inputButton 253
  #define toolbar___simulation___analogButton 254
  #define SimulationMenuInfo 255
  #define dialog___InputSimulation 256
  #define dialog___AnalogInputSimulation 257
  #define toolbar___simulation___netButton 258
  #define toolbar___simulation___output 259
  #define tool___constant 260
  #define toolbar___simulation 261
  #define dialog___DateInput 262
  #define toolbar___default___Fup 263
  #define menubar___Application 264
  #define toolbar___Kop 265
  #define menubar___Fup 266
  #define dialog___SelectDocumentsToSave 267
  #define dialog___GetFileName 268
  #define dialog___PageFormat 269
  #define dialog___GetPassword 270
  #define dialog___PropertyChangePassword 271
  #define dialog___PropertyGeneral 272
  #define dialog___PropertyStatistic 273
  #define dialog___PropertyComment 274
  #define dialog___BlockSelection 275
  #define dialog___InputNames 276
  #define dialog___ParameteringAllBlocks 277
  #define dialog___AutoCutLines 278
  #define dialog___FontAttributes 279
  #define dialog___Grid 280
  #define dialog___Zoom 281
  #define dialog___error___TransmissionError 282
  #define dialog___SetClock 283
  #define dialog___SummerWinter 284
  #define dialog___HardwareHoursCounter 285
  #define dialog___Hardware 286
  #define dialog___SetPowerOnScreen 287
  #define dialog___SwitchMode 288
  #define dialog___GeneralOptions 289
  #define dialog___MDIManagerSelection 290
  #define dialog___DisplayOptions 291
  #define dialog___PrintOptions 292
  #define dialog___ImportUploadOptions 293
  #define dialog___PortSelection 294
  #define dialog___SimulationOptions 295
  #define dialog___SimulationParameter 296
  #define dialog___LogoColorChooser 297
  #define dialog___ColorOptions 298
  #define help___tracking 299
  #define dialog___About 300
  #define block___High 301
  #define block___Low 302
  #define action___drawingDimension 303
  #define dialog___DrawingDimension 304
  #define block___AnalogInput 305
  #define block___AsiInput 306
  #define block___AsiOutput 307
  #define block___AnalogDeltaTrigger 308
  #define block___AnalogMarker 309
  #define block___AnalogCoil 310
  #define pdraw___app___createTools___selection 311
  #define pdraw___app___createTools___cutConnect 312
  #define pdraw___app___createTools___connectTT 313
  #define pdraw___app___createTools___blockConnec 314
  #define pdraw___app___createTools___simulation 315
  #define pdraw___app___createTools___onlineTest 316
  #define simulationControl___suspendResumeSimulation 317
  #define simulationControl___startSimulation 318
  #define simulationControl___stopSimulation 319
  #define dialog___DateInput 320
  #define simulationControl___stepSimulation 321
  #define simulationControl___setClock 322
  #define window___Message 323
  #define toolbar___blocks 324
  #define simulation___status 325
  #define info___copy 326
  #define info___delete 327
  #define short___block___Message 328
  #define toolbar___onlinetest 329
  #define onlineTestControl___startDevice 330
  #define onlineTestControl___stopDevice 331
  #define onlineTestControl___startStopWatching 332
  #define file_properties_password 333
  #define dialog___SelectDefaultEditor 334
  #define extras___options___language 335
  #define dialog___LookAndFeel 336
  #define whats___new___v7 337
  #define file___compare 338
  #define edit___EditUDFProperties 339
  #define format___FormatMenu___overview 340
  #define format___WrapText 341
  #define format___align___space 342
  #define format___align___down 343
  #define dialog___IPConfigure 344
  #define dialog___SlaveModeConfigure 345
  #define tool___transfer___ShowFWversion 346
  #define dialog___IOStatus 347
  #define tool___transfer___UploadDataLog 348
  #define dialog___Diagnostic 349
  #define dialog___EthernetConfigure 350
  #define dialog___VMConfigure 351
  #define dialog___UDFOption 352
  #define configuringEthernetConnections 353
  #define simulating_networkcommunication 354
  #define data___table 355
  #define block___NetworkNode 356
  #define block___AnalogNetworkNode 357
  #define block___SOutput 358
  #define block___SAnalogOutput 359
  #define block___LADnetworknodes 360
  #define block___LADanalognetworknodes 361
  #define block___LADslaveoutputs 362
  #define block___LADanalogslaveoutputs 363  
  #define block___AstronomicalClock 364
  #define block___StopWatch 365
  #define block___AnalogFilter 366
  #define block___MaxMin 367
  #define block___AverageValue 368
  #define block___DataLog 369
  #define block___DataLog___Configuring 370
  #define block___DataLog___Transfering 371
  #define block___DataLog___Opening 372
  #define block___UDF 373
  #define block___UDF___creating 374
  #define block___UDF___Saving 375
  #define block___UDF___Using 376
  #define block___UDF___Synchronizing 377
  #define dialog___editUDFParameter___IO 378
  #define dialog___editUDFParameter___Parameter 379
  #define dialog___editUDFParameter___Description 380
  #define dialog___CommunicationSetting 381
  #define dialog___CommunicationSetting___TCPSetting 382
  #define dialog___CommunicationSetting___PortSelection 383
  #define dialog___connectionConfigure___ClientConnection 384
  #define dialog___connectionConfigure___ServerConnection 385
  #define block___ShiftRegister___0BA7 386




  #define dialog___SelectDevice 387
  #define dialog___LogoOfflineGeneral 388
  #define dialog___HardwareSetting 389
  #define dialog___IOSettings 390
  #define dialog___InputNames 391
  #define dialog___Protection 392
  #define dialog___StartScreen 393
  #define dialog___MessageGlobalSetting 394
  #define dialog___AdditionalInfo 395
  #define dialog___Statistic 396
  #define dialog___ConnectionTransfer 397
  #define dialog___LogoOnlineGeneral 398
  #define dialog___IPConfigure 399
  #define dialog___SetClock 400
  #define dialog___SlaveModeConfigure 401
  #define dialog___ClearProgPwd 402
  #define dialog___SetPowerOnScreen 403
  #define dialog___HardwareHoursCounter 404
  #define dialog___UploadDatalog 405
  #define dialog___Diagnostic 406
  #define dialog___SummerWinter 407
  #define dialog___LogoUserProfile 408
  #define dialog___DynSrvIpFilterConfig 409
  #define dialog___ClockSyncEM 410
  #define extra___transfer___startDeviceState 411
  #define extra___transfer___stopDeviceState 412
  #define format___align___spaceacross 413
  #define format___align___spacedown 414
  #define edit___marktofront 415
  #define edit___marktoback 416
  #define window___splitHorizontal 417
  #define window___splitVertical 418
  #define parameterBox___hiddenParameterLine 419
  #define parameterBox___expandParameterBox 420
  #define parameterBox___collapseParameterBox 421
  #define diagram___mode___tree 422
  #define editor___name___fupEditor 423
  #define network___project___tree 424
  #define palette___project___root___add 425
  #define window___go___online 426
  #define window___go___offline 427
  #define editor___name___projectEditor 428
  #define format___base 429
  #define action___drawingDimension 430
  #define pdraw___app___createTools___onlineTest 431
  #define file___convertToKop 432
  #define dialog___ListSeparatorOption 433
  #define toolbar___networkdrawing 434
  #define dialog___AutoCutLines 435
  #define extras___options___language 436
  #define format___align___automatically 437
  #define format___align___vertical 438
  #define format___align___horizontal 439
  #define dialog___PCSetting 440
  #define dialog___connectionConfigure___logo2logo 441
  #define dialog___connectionConfigure___logo2nonlogo 442
  #define dialog___device___properties___SimaticPanelDevice 443
  #define dialog___device___properties___LogoTDEDevice 444
  #define dialog___device___properties___S7Device 445
  #define dialog___device___properties___Logo8SlaveDevice 446
  #define dialog___device___properties___Logo7SlaveDevice 447
  #define dialog___connectionConfigure___uneditable 448
  #define dialog___MessageGlobalSetting 449
  #define dialog___LogoComments 450



  #define view___diagram___mode 451
  #define whats___new___v8 452
  #define introducing___creation___project 453
  #define create___new___project 454
  #define create___a___project 455
  #define add___a___device 456
  #define devices 457
  #define open___save___project 458
  #define two___side___programming 459
  #define config___pc 460
  #define config___logo___offline 461
  #define config___logo___online 462
  #define config___other 463
  #define detect___online___status 464
  #define config___unknown___devices 465
  #define two___side___programming 466
  #define Ethernet___logo___logo 467
  #define Ethernet___logo___remote 468
  #define Ethernet___logo___logoslave 469
  #define Ethernet___logo___S7 470
  #define Ethernet___logo___HMI 471
  #define Ethernet___logo___nonproject 472
  #define diagram___overview 473
  #define project___overview 474
  #define format___align___verticalspace 475
  #define format___align___horizontalspace 476
  #define view___network___project 477
  #define view___toolbar 478
  #define view___tree 479
  #define parameter___box___overview 480
  #define parameter___box___edit 481
  #define message___text___0BA2 482
  #define message___text___0BA4 483
  #define message___text___0BA6 484
  #define message___text___0BA4 485
  #define message___text___0BA6 486
  #define security___information 487
  #define security___note 488

#define dialog___NtpTimeConfigure 489
#define dialog___device___properties___ModbusDevice 490
#define block___Float2Integer 491
#define block___Integer2Float 492
#define dialog___ModbusConfiguration 493
#define dialog___modbusConnectionConfigure___ModbusClientConnection 494
#define window___go___hideConnection 495
#define DE___siemens___ad___logo___dialog___TDEOnlineSetting 496
#define DE___siemens___ad___logo___dialog___TDEOfflineSetting 497
#define dialog___modbusConnectionConfigure___ModbusServerConnection 498

#define Data___Log_Profile 499
#define block___DataLogProfile 500
#define networkProject___tree___node___newDevice 501
#define dialog___Grid 502
#define dialog___LogoModbusConfiguration 503
#define dialog___LogoSettingInterface 504
#define dialog___device___properties___ModbusDevice 505
#define dialog___device___properties___Logo8Update1SlaveDevice 506
#define dialog___UnknownDeviceSetting 507
#define dialog___connectionConfigure___logo2nonlogo 508
#define dialog___IndependentInterface 509
 
#define dialog___AccessControlSettingsWrapperD 510
#define dialog___CloudTransferSetting 511
#define dialog___CloudConnectionSetting 512
#define dialog___CertificateSettingD 513
#define dialog___EditProjectProperties 514

